#!/usr/bin/env node
// Generates decks/spanish-traveler.json from inline data.
// Run: node scripts/generate-deck.js

const fs = require("fs");
const path = require("path");

const meta = {
  id: "spanish-traveler",
  name: "Spanish for South American Travelers",
  description: "~500 words and phrases for a beginner trip to South America. Sequenced from cognates to survival phrases to real-world scenarios.",
  version: "1.0.0",
  frontLang: "es",
  frontLocale: "es-419",
  backLang: "en",
  license: "MIT",
  attribution: "Original curation. Word frequency cross-referenced against doozan/spanish_data (CC-BY-4.0) and the RAE CREA corpus.",
  ttsRate: 0.85,
};

const units = [
  { id: "u01-cognates", name: "1 · Free wins (cognates)", blurb: "Words you basically already know from English." },
  { id: "u02-greetings", name: "2 · Greetings & politeness", blurb: "The first 30 seconds of every interaction." },
  { id: "u03-survival", name: "3 · Survival phrases", blurb: "\"I don't understand\", \"where is the bathroom\", \"help\"." },
  { id: "u04-pronouns", name: "4 · Pronouns & articles", blurb: "The glue words that hold sentences together." },
  { id: "u05-numbers", name: "5 · Numbers & time", blurb: "Counting, days, telling time." },
  { id: "u06-verbs", name: "6 · Top verbs", blurb: "The 50 most-used Spanish verbs (infinitive + yo/tú present)." },
  { id: "u07-questions", name: "7 · Question words & adverbs", blurb: "How to ask and qualify." },
  { id: "u08-transit", name: "8 · Directions & transit", blurb: "Getting around: buses, streets, navigation." },
  { id: "u09-food", name: "9 · Food & restaurants", blurb: "Ordering, reading menus, dietary needs." },
  { id: "u10-lodging", name: "10 · Lodging", blurb: "Hotels, hostels, Airbnb check-in vocab." },
  { id: "u11-money", name: "11 · Money & shopping", blurb: "Prices, ATMs, bargaining, receipts." },
  { id: "u12-emergency", name: "12 · Emergency & health", blurb: "Doctor visits, pharmacies, safety." },
  { id: "u13-people", name: "13 · People & family", blurb: "Talking about and to people." },
  { id: "u14-adjectives", name: "14 · Common adjectives", blurb: "Describing things." },
  { id: "u15-connectors", name: "15 · Prepositions & connectors", blurb: "Joining ideas together." },
  { id: "u16-body", name: "16 · Body & clothing", blurb: "Useful for shopping and doctors." },
];

// Data format: [front, back, pos, tags[], exFront?, exBack?]
const cardData = {
  "u01-cognates": [
    ["el hospital", "the hospital", "noun", ["cognate","health"], "El hospital está cerca.", "The hospital is nearby."],
    ["el taxi", "the taxi", "noun", ["cognate","transit"], "Necesito un taxi.", "I need a taxi."],
    ["el hotel", "the hotel", "noun", ["cognate","lodging"], "El hotel es muy bueno.", "The hotel is very good."],
    ["el restaurante", "the restaurant", "noun", ["cognate","food"], "El restaurante cierra a las diez.", "The restaurant closes at ten."],
    ["el banco", "the bank", "noun", ["cognate","money"], "¿Hay un banco cerca?", "Is there a bank nearby?"],
    ["el doctor", "the doctor", "noun", ["cognate","health"], "Necesito ver a un doctor.", "I need to see a doctor."],
    ["importante", "important", "adj", ["cognate"], "Es muy importante.", "It's very important."],
    ["posible", "possible", "adj", ["cognate"], "¿Es posible?", "Is it possible?"],
    ["imposible", "impossible", "adj", ["cognate"], "No es imposible.", "It's not impossible."],
    ["el problema", "the problem", "noun", ["cognate"], "No hay problema.", "No problem."],
    ["el momento", "the moment", "noun", ["cognate"], "Un momento, por favor.", "One moment, please."],
    ["la persona", "the person", "noun", ["cognate","people"], "Es una buena persona.", "They're a good person."],
    ["la familia", "the family", "noun", ["cognate","people"], "Mi familia es grande.", "My family is big."],
    ["la idea", "the idea", "noun", ["cognate"], "¡Buena idea!", "Good idea!"],
    ["la oficina", "the office", "noun", ["cognate"], "La oficina está cerrada.", "The office is closed."],
    ["el parque", "the park", "noun", ["cognate"], "Vamos al parque.", "Let's go to the park."],
    ["la plaza", "the plaza / town square", "noun", ["cognate","transit"], "Nos vemos en la plaza.", "See you at the plaza."],
    ["el museo", "the museum", "noun", ["cognate"], "El museo es gratis hoy.", "The museum is free today."],
    ["el supermercado", "the supermarket", "noun", ["cognate","shopping"], "Voy al supermercado.", "I'm going to the supermarket."],
    ["la farmacia", "the pharmacy", "noun", ["cognate","health"], "¿Dónde hay una farmacia?", "Where is there a pharmacy?"],
    ["el café", "the coffee / café", "noun", ["cognate","food"], "Un café, por favor.", "A coffee, please."],
    ["el animal", "the animal", "noun", ["cognate"], null, null],
    ["la capital", "the capital", "noun", ["cognate"], "Lima es la capital de Perú.", "Lima is the capital of Peru."],
    ["la música", "the music", "noun", ["cognate"], "Me gusta la música.", "I like music."],
    ["el número", "the number", "noun", ["cognate"], "¿Cuál es tu número?", "What's your number?"],
    ["el teléfono", "the telephone", "noun", ["cognate"], "¿Tiene teléfono?", "Do you have a phone?"],
    ["la computadora", "the computer", "noun", ["cognate"], null, null],
    ["el internet", "the internet", "noun", ["cognate"], "¿Hay internet aquí?", "Is there internet here?"],
    ["la foto", "the photo", "noun", ["cognate"], "¿Puedo tomar una foto?", "Can I take a photo?"],
    ["la fruta", "the fruit", "noun", ["cognate","food"], "Me gusta la fruta fresca.", "I like fresh fruit."],
    ["el mapa", "the map", "noun", ["cognate","transit"], "¿Tiene un mapa?", "Do you have a map?"],
    ["el pasaporte", "the passport", "noun", ["cognate","travel"], "Necesito mi pasaporte.", "I need my passport."],
    ["el/la turista", "the tourist", "noun", ["cognate","travel"], "Soy turista.", "I'm a tourist."],
    ["el aeropuerto", "the airport", "noun", ["cognate","transit"], "¿Cómo llego al aeropuerto?", "How do I get to the airport?"],
    ["el accidente", "the accident", "noun", ["cognate","emergency"], "Hubo un accidente.", "There was an accident."],
    ["el chocolate", "the chocolate", "noun", ["cognate","food"], null, null],
    ["la información", "the information", "noun", ["cognate"], "Necesito más información.", "I need more information."],
    ["normal", "normal", "adj", ["cognate"], "Es normal aquí.", "It's normal here."],
    ["especial", "special", "adj", ["cognate"], null, null],
    ["natural", "natural", "adj", ["cognate"], "Es jugo natural.", "It's fresh juice."],
  ],
  "u02-greetings": [
    ["hola", "hello / hi", "phrase", ["greetings"], "¡Hola! ¿Cómo estás?", "Hi! How are you?"],
    ["buenos días", "good morning", "phrase", ["greetings"], "Buenos días, señora.", "Good morning, ma'am."],
    ["buenas tardes", "good afternoon", "phrase", ["greetings"], null, null],
    ["buenas noches", "good evening / good night", "phrase", ["greetings"], null, null],
    ["adiós", "goodbye", "phrase", ["greetings"], "Adiós, hasta pronto.", "Goodbye, see you soon."],
    ["hasta luego", "see you later", "phrase", ["greetings"], null, null],
    ["hasta mañana", "see you tomorrow", "phrase", ["greetings"], null, null],
    ["gracias", "thank you", "phrase", ["greetings"], "Muchas gracias por su ayuda.", "Thank you very much for your help."],
    ["muchas gracias", "thank you very much", "phrase", ["greetings"], null, null],
    ["de nada", "you're welcome", "phrase", ["greetings"], null, null],
    ["por favor", "please", "phrase", ["greetings"], "Un agua, por favor.", "A water, please."],
    ["perdón", "pardon / excuse me", "phrase", ["greetings"], "Perdón, ¿puedo pasar?", "Excuse me, may I pass?"],
    ["lo siento", "I'm sorry", "phrase", ["greetings"], "Lo siento mucho.", "I'm very sorry."],
    ["disculpe", "excuse me (formal)", "phrase", ["greetings"], "Disculpe, ¿dónde está el baño?", "Excuse me, where is the bathroom?"],
    ["¿cómo estás?", "how are you? (informal)", "phrase", ["greetings"], null, null],
    ["¿cómo está usted?", "how are you? (formal)", "phrase", ["greetings"], null, null],
    ["bien", "good / well", "adv", ["greetings"], "Estoy bien, gracias.", "I'm good, thanks."],
    ["muy bien", "very good / very well", "phrase", ["greetings"], null, null],
    ["mal", "bad / badly", "adv", ["greetings"], "Me siento mal.", "I feel bad."],
    ["mucho gusto", "nice to meet you", "phrase", ["greetings"], null, null],
    ["¿cómo te llamas?", "what's your name? (informal)", "phrase", ["greetings"], null, null],
    ["me llamo...", "my name is...", "phrase", ["greetings"], "Me llamo Carlos.", "My name is Carlos."],
    ["soy de...", "I'm from...", "phrase", ["greetings","people"], "Soy de los Estados Unidos.", "I'm from the United States."],
    ["sí", "yes", "adv", [], null, null],
    ["no", "no / not", "adv", [], null, null],
    ["claro", "of course / sure", "adv", [], "Claro que sí.", "Of course."],
    ["tal vez", "maybe / perhaps", "adv", [], "Tal vez mañana.", "Maybe tomorrow."],
    ["¡salud!", "cheers! / bless you!", "phrase", ["greetings"], null, null],
    ["con permiso", "excuse me (passing by)", "phrase", ["greetings"], null, null],
    ["bienvenido/a", "welcome", "adj", ["greetings"], "¡Bienvenido a Colombia!", "Welcome to Colombia!"],
  ],
  "u03-survival": [
    ["no entiendo", "I don't understand", "phrase", ["survival"], null, null],
    ["no sé", "I don't know", "phrase", ["survival"], null, null],
    ["no hablo español", "I don't speak Spanish", "phrase", ["survival"], "No hablo español muy bien.", "I don't speak Spanish very well."],
    ["¿habla inglés?", "do you speak English?", "phrase", ["survival"], null, null],
    ["más despacio, por favor", "slower, please", "phrase", ["survival"], null, null],
    ["¿puede repetir?", "can you repeat that?", "phrase", ["survival"], null, null],
    ["¿qué significa?", "what does it mean?", "phrase", ["survival"], "¿Qué significa esta palabra?", "What does this word mean?"],
    ["¿cómo se dice...?", "how do you say...?", "phrase", ["survival"], "¿Cómo se dice 'water' en español?", "How do you say 'water' in Spanish?"],
    ["ayuda", "help", "noun", ["survival","emergency"], "¡Ayuda!", "Help!"],
    ["necesito ayuda", "I need help", "phrase", ["survival","emergency"], null, null],
    ["¿dónde está el baño?", "where is the bathroom?", "phrase", ["survival"], null, null],
    ["no tengo", "I don't have", "phrase", ["survival"], "No tengo efectivo.", "I don't have cash."],
    ["tengo hambre", "I'm hungry", "phrase", ["survival"], null, null],
    ["tengo sed", "I'm thirsty", "phrase", ["survival"], null, null],
    ["tengo frío", "I'm cold", "phrase", ["survival"], null, null],
    ["tengo calor", "I'm hot", "phrase", ["survival"], null, null],
    ["estoy cansado/a", "I'm tired", "phrase", ["survival"], null, null],
    ["estoy perdido/a", "I'm lost", "phrase", ["survival"], "Estoy perdido, ¿me puede ayudar?", "I'm lost, can you help me?"],
    ["¿me puede ayudar?", "can you help me?", "phrase", ["survival"], null, null],
    ["¿puedo...?", "can I...? / may I...?", "phrase", ["survival"], "¿Puedo sentarme aquí?", "Can I sit here?"],
    ["un momento", "one moment", "phrase", ["survival"], null, null],
    ["está bien", "it's okay / alright", "phrase", ["survival"], null, null],
    ["no importa", "it doesn't matter", "phrase", ["survival"], null, null],
    ["no se preocupe", "don't worry", "phrase", ["survival"], null, null],
    ["es urgente", "it's urgent", "phrase", ["survival","emergency"], null, null],
    ["¿es seguro?", "is it safe?", "phrase", ["survival"], "¿Es seguro caminar de noche?", "Is it safe to walk at night?"],
    ["déjeme en paz", "leave me alone", "phrase", ["survival"], null, null],
    ["no quiero", "I don't want (it)", "phrase", ["survival"], "No quiero, gracias.", "I don't want it, thanks."],
    ["basta", "enough / stop", "phrase", ["survival"], null, null],
    ["¿cuánto cuesta?", "how much does it cost?", "phrase", ["survival","money"], "¿Cuánto cuesta esto?", "How much does this cost?"],
  ],
  "u04-pronouns": [
    ["yo", "I", "pron", ["pronoun"], "Yo quiero ir.", "I want to go."],
    ["tú", "you (informal)", "pron", ["pronoun"], null, null],
    ["él", "he", "pron", ["pronoun"], null, null],
    ["ella", "she", "pron", ["pronoun"], null, null],
    ["usted", "you (formal)", "pron", ["pronoun"], "¿Usted es de aquí?", "Are you from here?"],
    ["nosotros/as", "we", "pron", ["pronoun"], null, null],
    ["ustedes", "you all (Latin America)", "pron", ["pronoun"], null, null],
    ["ellos/as", "they", "pron", ["pronoun"], null, null],
    ["mi / mis", "my", "det", ["pronoun"], "Mi nombre es...", "My name is..."],
    ["tu / tus", "your (informal)", "det", ["pronoun"], null, null],
    ["su / sus", "his / her / your (formal) / their", "det", ["pronoun"], "Su casa es bonita.", "Their house is pretty."],
    ["nuestro/a", "our", "det", ["pronoun"], null, null],
    ["este / esta", "this", "det", ["pronoun"], "Este es mi hotel.", "This is my hotel."],
    ["ese / esa", "that", "det", ["pronoun"], "Esa calle es peligrosa.", "That street is dangerous."],
    ["esto", "this (thing)", "pron", ["pronoun"], "¿Qué es esto?", "What is this?"],
    ["eso", "that (thing)", "pron", ["pronoun"], "Eso es correcto.", "That's correct."],
    ["el / la", "the (masc. / fem.)", "det", ["article"], null, null],
    ["los / las", "the (plural)", "det", ["article"], null, null],
    ["un / una", "a / an", "det", ["article"], null, null],
    ["algo", "something", "pron", ["pronoun"], "¿Hay algo más?", "Is there anything else?"],
    ["nada", "nothing", "pron", ["pronoun"], "No necesito nada.", "I don't need anything."],
    ["todo", "everything / all", "pron", ["pronoun"], "Todo está bien.", "Everything is fine."],
    ["otro/a", "another / other", "det", ["pronoun"], "¿Tiene otro color?", "Do you have another color?"],
    ["mismo/a", "same", "adj", ["pronoun"], "Es lo mismo.", "It's the same."],
  ],
  "u05-numbers": [
    ["uno", "one / 1", "num", ["numbers"], null, null],
    ["dos", "two / 2", "num", ["numbers"], null, null],
    ["tres", "three / 3", "num", ["numbers"], null, null],
    ["cuatro", "four / 4", "num", ["numbers"], null, null],
    ["cinco", "five / 5", "num", ["numbers"], null, null],
    ["seis", "six / 6", "num", ["numbers"], null, null],
    ["siete", "seven / 7", "num", ["numbers"], null, null],
    ["ocho", "eight / 8", "num", ["numbers"], null, null],
    ["nueve", "nine / 9", "num", ["numbers"], null, null],
    ["diez", "ten / 10", "num", ["numbers"], null, null],
    ["once", "eleven / 11", "num", ["numbers"], null, null],
    ["doce", "twelve / 12", "num", ["numbers"], null, null],
    ["quince", "fifteen / 15", "num", ["numbers"], null, null],
    ["veinte", "twenty / 20", "num", ["numbers"], null, null],
    ["treinta", "thirty / 30", "num", ["numbers"], null, null],
    ["cuarenta", "forty / 40", "num", ["numbers"], null, null],
    ["cincuenta", "fifty / 50", "num", ["numbers"], null, null],
    ["cien", "one hundred / 100", "num", ["numbers"], "Cuesta cien pesos.", "It costs one hundred pesos."],
    ["mil", "one thousand / 1000", "num", ["numbers"], null, null],
    ["primero/a", "first", "adj", ["numbers"], "La primera calle a la derecha.", "The first street on the right."],
    ["segundo/a", "second", "adj", ["numbers"], null, null],
    ["último/a", "last", "adj", ["numbers"], "El último autobús.", "The last bus."],
    ["hoy", "today", "adv", ["time"], "¿Qué día es hoy?", "What day is today?"],
    ["mañana", "tomorrow / morning", "noun", ["time"], "Hasta mañana.", "See you tomorrow."],
    ["ayer", "yesterday", "adv", ["time"], null, null],
    ["ahora", "now", "adv", ["time"], "Ahora no puedo.", "I can't right now."],
    ["después", "after / later", "adv", ["time"], "Después de comer.", "After eating."],
    ["antes", "before", "adv", ["time"], "Antes de las tres.", "Before three."],
    ["temprano", "early", "adv", ["time"], null, null],
    ["tarde", "late / afternoon", "adv", ["time"], "Es tarde.", "It's late."],
    ["la hora", "the hour / time", "noun", ["time"], "¿Qué hora es?", "What time is it?"],
    ["el minuto", "the minute", "noun", ["time"], null, null],
    ["el día", "the day", "noun", ["time"], "Todo el día.", "All day."],
    ["la semana", "the week", "noun", ["time"], "La próxima semana.", "Next week."],
    ["el mes", "the month", "noun", ["time"], null, null],
    ["el año", "the year", "noun", ["time"], null, null],
    ["lunes", "Monday", "noun", ["time","days"], null, null],
    ["martes", "Tuesday", "noun", ["time","days"], null, null],
    ["miércoles", "Wednesday", "noun", ["time","days"], null, null],
    ["jueves", "Thursday", "noun", ["time","days"], null, null],
    ["viernes", "Friday", "noun", ["time","days"], null, null],
    ["sábado", "Saturday", "noun", ["time","days"], null, null],
    ["domingo", "Sunday", "noun", ["time","days"], null, null],
  ],
  "u06-verbs": [
    ["ser", "to be (identity/nature)", "verb", ["core-verb"], "Soy estudiante.", "I am a student."],
    ["estar", "to be (state/location)", "verb", ["core-verb"], "Estoy aquí.", "I am here."],
    ["tener", "to have", "verb", ["core-verb"], "Tengo dos hermanos.", "I have two brothers."],
    ["hacer", "to do / to make", "verb", ["core-verb"], "¿Qué haces?", "What are you doing?"],
    ["ir", "to go", "verb", ["core-verb"], "Voy al centro.", "I'm going downtown."],
    ["decir", "to say / to tell", "verb", ["core-verb"], "¿Cómo se dice?", "How do you say it?"],
    ["poder", "to be able to / can", "verb", ["core-verb"], "¿Puedo entrar?", "Can I come in?"],
    ["saber", "to know (facts)", "verb", ["core-verb"], "No sé dónde está.", "I don't know where it is."],
    ["ver", "to see", "verb", ["core-verb"], "¿Puedes ver?", "Can you see?"],
    ["dar", "to give", "verb", ["core-verb"], "¿Me da la cuenta?", "Can you give me the bill?"],
    ["querer", "to want / to love", "verb", ["core-verb"], "Quiero un café.", "I want a coffee."],
    ["llegar", "to arrive", "verb", ["core-verb"], "¿A qué hora llega?", "What time does it arrive?"],
    ["pasar", "to pass / to happen", "verb", ["core-verb"], "¿Qué pasó?", "What happened?"],
    ["deber", "to must / to owe", "verb", ["core-verb"], "Debo irme.", "I must go."],
    ["poner", "to put / to place", "verb", ["core-verb"], "¿Dónde lo pongo?", "Where do I put it?"],
    ["quedar", "to stay / to remain / to be located", "verb", ["core-verb"], "¿Dónde queda?", "Where is it located?"],
    ["creer", "to believe / to think", "verb", ["core-verb"], "Creo que sí.", "I think so."],
    ["hablar", "to speak / to talk", "verb", ["core-verb"], "¿Habla inglés?", "Do you speak English?"],
    ["llevar", "to carry / to take / to wear", "verb", ["core-verb"], "Llevo una mochila.", "I'm carrying a backpack."],
    ["dejar", "to leave / to let", "verb", ["core-verb"], "Déjame pensar.", "Let me think."],
    ["seguir", "to follow / to continue", "verb", ["core-verb"], "Siga derecho.", "Continue straight."],
    ["encontrar", "to find", "verb", ["core-verb"], "No puedo encontrarlo.", "I can't find it."],
    ["llamar", "to call", "verb", ["core-verb"], "¿Puedo llamar un taxi?", "Can I call a taxi?"],
    ["venir", "to come", "verb", ["core-verb"], "¿De dónde vienes?", "Where do you come from?"],
    ["pensar", "to think", "verb", ["core-verb"], "Déjame pensar.", "Let me think."],
    ["salir", "to leave / to go out", "verb", ["core-verb"], "Salgo a las ocho.", "I leave at eight."],
    ["volver", "to return / to come back", "verb", ["core-verb"], "Vuelvo mañana.", "I'll be back tomorrow."],
    ["tomar", "to take / to drink", "verb", ["core-verb"], "Voy a tomar un café.", "I'm going to have a coffee."],
    ["conocer", "to know (people/places)", "verb", ["core-verb"], "¿Conoces Buenos Aires?", "Do you know Buenos Aires?"],
    ["vivir", "to live", "verb", ["core-verb"], "¿Dónde vives?", "Where do you live?"],
    ["sentir", "to feel", "verb", ["core-verb"], "Me siento bien.", "I feel good."],
    ["mirar", "to look / to watch", "verb", ["core-verb"], "Mira eso.", "Look at that."],
    ["esperar", "to wait / to hope", "verb", ["core-verb"], "Espera un momento.", "Wait a moment."],
    ["buscar", "to look for / to search", "verb", ["core-verb"], "Busco un hotel.", "I'm looking for a hotel."],
    ["entrar", "to enter", "verb", ["core-verb"], "¿Puedo entrar?", "May I come in?"],
    ["trabajar", "to work", "verb", ["core-verb"], "Trabajo aquí.", "I work here."],
    ["escribir", "to write", "verb", ["core-verb"], "¿Puede escribirlo?", "Can you write it down?"],
    ["perder", "to lose / to miss", "verb", ["core-verb"], "Perdí mi billetera.", "I lost my wallet."],
    ["entender", "to understand", "verb", ["core-verb"], "¿Entiende?", "Do you understand?"],
    ["pedir", "to ask for / to order", "verb", ["core-verb"], "Quiero pedir la cuenta.", "I want to ask for the bill."],
    ["recibir", "to receive", "verb", ["core-verb"], null, null],
    ["recordar", "to remember", "verb", ["core-verb"], "No recuerdo.", "I don't remember."],
    ["terminar", "to finish", "verb", ["core-verb"], "Ya terminé.", "I already finished."],
    ["comenzar", "to begin", "verb", ["core-verb"], "¿A qué hora comienza?", "What time does it start?"],
    ["abrir", "to open", "verb", ["core-verb"], "¿A qué hora abren?", "What time do they open?"],
    ["cerrar", "to close", "verb", ["core-verb"], "¿A qué hora cierran?", "What time do they close?"],
    ["comer", "to eat", "verb", ["core-verb"], "¿Dónde podemos comer?", "Where can we eat?"],
    ["beber", "to drink", "verb", ["core-verb"], "¿Qué quieres beber?", "What do you want to drink?"],
    ["dormir", "to sleep", "verb", ["core-verb"], "Necesito dormir.", "I need to sleep."],
    ["comprar", "to buy", "verb", ["core-verb"], "¿Dónde puedo comprar eso?", "Where can I buy that?"],
  ],
  "u07-questions": [
    ["¿qué?", "what?", "adv", ["question"], null, null],
    ["¿quién?", "who?", "adv", ["question"], "¿Quién es?", "Who is it?"],
    ["¿dónde?", "where?", "adv", ["question"], null, null],
    ["¿cuándo?", "when?", "adv", ["question"], null, null],
    ["¿cómo?", "how?", "adv", ["question"], null, null],
    ["¿por qué?", "why?", "adv", ["question"], null, null],
    ["porque", "because", "conj", ["question"], "Porque tengo hambre.", "Because I'm hungry."],
    ["¿cuál?", "which? / which one?", "adv", ["question"], "¿Cuál prefieres?", "Which do you prefer?"],
    ["¿cuánto/a?", "how much?", "adv", ["question"], null, null],
    ["¿cuántos/as?", "how many?", "adv", ["question"], "¿Cuántas personas?", "How many people?"],
    ["también", "also / too", "adv", ["frequency"], "Yo también.", "Me too."],
    ["muy", "very", "adv", ["frequency"], "Es muy caro.", "It's very expensive."],
    ["mucho/a", "a lot / much", "adv", ["frequency"], null, null],
    ["poco", "a little / few", "adv", ["frequency"], "Un poco de agua.", "A little water."],
    ["siempre", "always", "adv", ["frequency"], null, null],
    ["nunca", "never", "adv", ["frequency"], null, null],
    ["aquí", "here", "adv", ["place"], "Aquí está.", "Here it is."],
    ["allí / ahí", "there", "adv", ["place"], "Está allí.", "It's over there."],
    ["ya", "already / now", "adv", ["time"], "Ya llegó.", "It already arrived."],
    ["todavía", "still / yet", "adv", ["time"], "Todavía no.", "Not yet."],
    ["más", "more / most", "adv", ["comparison"], "Más grande.", "Bigger."],
    ["menos", "less / fewer", "adv", ["comparison"], "Menos caro.", "Less expensive."],
    ["mejor", "better / best", "adv", ["comparison"], "El mejor restaurante.", "The best restaurant."],
    ["peor", "worse / worst", "adv", ["comparison"], null, null],
    ["solo", "only / just / alone", "adv", [], "Solo uno.", "Just one."],
  ],
  "u08-transit": [
    ["la calle", "the street", "noun", ["transit"], "¿Cuál es esta calle?", "What street is this?"],
    ["la avenida", "the avenue", "noun", ["transit"], null, null],
    ["la esquina", "the corner", "noun", ["transit"], "En la esquina.", "On the corner."],
    ["el semáforo", "the traffic light", "noun", ["transit"], "En el semáforo, gire a la derecha.", "At the traffic light, turn right."],
    ["a la izquierda", "to the left", "phrase", ["transit","directions"], null, null],
    ["a la derecha", "to the right", "phrase", ["transit","directions"], null, null],
    ["derecho / recto", "straight ahead", "adv", ["transit","directions"], "Siga derecho dos cuadras.", "Go straight two blocks."],
    ["cerca", "near / close", "adv", ["transit"], "¿Está cerca?", "Is it close?"],
    ["lejos", "far", "adv", ["transit"], "Está muy lejos.", "It's very far."],
    ["la cuadra", "the block (city)", "noun", ["transit"], "A dos cuadras de aquí.", "Two blocks from here."],
    ["norte", "north", "noun", ["transit","directions"], null, null],
    ["sur", "south", "noun", ["transit","directions"], null, null],
    ["¿dónde está...?", "where is...?", "phrase", ["transit"], null, null],
    ["¿cómo llego a...?", "how do I get to...?", "phrase", ["transit"], "¿Cómo llego al centro?", "How do I get downtown?"],
    ["el autobús", "the bus", "noun", ["transit"], "¿Cuál autobús va al centro?", "Which bus goes downtown?"],
    ["el tren", "the train", "noun", ["transit"], null, null],
    ["el metro", "the metro / subway", "noun", ["transit"], "¿Dónde está la estación de metro?", "Where is the metro station?"],
    ["el colectivo", "the minibus (Argentina)", "noun", ["transit"], null, null],
    ["la bicicleta", "the bicycle", "noun", ["transit"], null, null],
    ["el carro / coche", "the car", "noun", ["transit"], null, null],
    ["la parada", "the stop (bus)", "noun", ["transit"], "¿Dónde está la parada?", "Where is the bus stop?"],
    ["la estación", "the station", "noun", ["transit"], null, null],
    ["el boleto", "the ticket", "noun", ["transit"], "Un boleto, por favor.", "One ticket, please."],
    ["ida", "one-way", "noun", ["transit"], null, null],
    ["ida y vuelta", "round trip", "phrase", ["transit"], "Un boleto de ida y vuelta.", "A round-trip ticket."],
    ["la salida", "the exit / departure", "noun", ["transit"], "¿Dónde está la salida?", "Where is the exit?"],
    ["la llegada", "the arrival", "noun", ["transit"], null, null],
    ["el vuelo", "the flight", "noun", ["transit"], "Mi vuelo sale a las tres.", "My flight leaves at three."],
    ["el equipaje", "the luggage", "noun", ["transit","lodging"], null, null],
    ["la maleta", "the suitcase", "noun", ["transit","lodging"], null, null],
    ["caminar", "to walk", "verb", ["transit"], "¿Se puede caminar?", "Can you walk there?"],
    ["subir", "to get on / go up", "verb", ["transit"], null, null],
    ["bajar", "to get off / go down", "verb", ["transit"], "¿Dónde bajo?", "Where do I get off?"],
  ],
  "u09-food": [
    ["la comida", "the food / meal", "noun", ["food"], null, null],
    ["el desayuno", "breakfast", "noun", ["food"], "¿A qué hora es el desayuno?", "What time is breakfast?"],
    ["el almuerzo", "lunch", "noun", ["food"], null, null],
    ["la cena", "dinner", "noun", ["food"], null, null],
    ["la mesa", "the table", "noun", ["food"], "Una mesa para dos, por favor.", "A table for two, please."],
    ["el menú / la carta", "the menu", "noun", ["food"], "El menú, por favor.", "The menu, please."],
    ["el mesero / camarero", "the waiter", "noun", ["food"], null, null],
    ["la cuenta", "the bill / check", "noun", ["food","money"], "La cuenta, por favor.", "The check, please."],
    ["la propina", "the tip", "noun", ["food","money"], null, null],
    ["el agua", "water", "noun", ["food","drink"], "Un vaso de agua, por favor.", "A glass of water, please."],
    ["agua sin gas", "still water", "phrase", ["food","drink"], null, null],
    ["agua con gas", "sparkling water", "phrase", ["food","drink"], null, null],
    ["el café", "coffee", "noun", ["food","drink"], null, null],
    ["el té", "tea", "noun", ["food","drink"], null, null],
    ["la leche", "milk", "noun", ["food","drink"], null, null],
    ["el jugo", "juice (Latin America)", "noun", ["food","drink"], "Un jugo de naranja.", "An orange juice."],
    ["la cerveza", "beer", "noun", ["food","drink"], "Dos cervezas, por favor.", "Two beers, please."],
    ["el vino", "wine", "noun", ["food","drink"], null, null],
    ["el pan", "bread", "noun", ["food"], null, null],
    ["la mantequilla", "butter", "noun", ["food"], null, null],
    ["el azúcar", "sugar", "noun", ["food"], null, null],
    ["la sal", "salt", "noun", ["food"], null, null],
    ["el queso", "cheese", "noun", ["food"], null, null],
    ["el huevo", "egg", "noun", ["food"], null, null],
    ["el pollo", "chicken", "noun", ["food"], null, null],
    ["la carne", "meat", "noun", ["food"], null, null],
    ["el pescado", "fish (food)", "noun", ["food"], null, null],
    ["la carne de res", "beef", "noun", ["food"], null, null],
    ["el arroz", "rice", "noun", ["food"], null, null],
    ["la papa", "potato (Latin America)", "noun", ["food"], null, null],
    ["la ensalada", "salad", "noun", ["food"], null, null],
    ["la sopa", "soup", "noun", ["food"], null, null],
    ["el postre", "dessert", "noun", ["food"], null, null],
    ["el helado", "ice cream", "noun", ["food"], null, null],
    ["la manzana", "apple", "noun", ["food","fruit"], null, null],
    ["la naranja", "orange", "noun", ["food","fruit"], null, null],
    ["el plátano", "banana / plantain", "noun", ["food","fruit"], null, null],
    ["el tomate", "tomato", "noun", ["food"], null, null],
    ["los frijoles", "beans", "noun", ["food"], null, null],
    ["picante", "spicy", "adj", ["food"], "¿Es picante?", "Is it spicy?"],
    ["dulce", "sweet", "adj", ["food"], null, null],
    ["salado/a", "salty", "adj", ["food"], null, null],
    ["rico/a", "delicious / rich", "adj", ["food"], "¡Está muy rico!", "It's really delicious!"],
    ["¿qué recomienda?", "what do you recommend?", "phrase", ["food"], null, null],
    ["soy vegetariano/a", "I'm vegetarian", "phrase", ["food","diet"], null, null],
    ["sin carne", "without meat", "phrase", ["food","diet"], null, null],
    ["tengo alergia a...", "I'm allergic to...", "phrase", ["food","health"], "Tengo alergia a los mariscos.", "I'm allergic to seafood."],
    ["el plato del día", "the daily special", "phrase", ["food"], null, null],
  ],
  "u10-lodging": [
    ["el hotel", "hotel", "noun", ["lodging"], null, null],
    ["el hostal", "hostel", "noun", ["lodging"], null, null],
    ["la habitación", "the room", "noun", ["lodging"], "¿Tiene habitaciones disponibles?", "Do you have rooms available?"],
    ["individual", "single (room)", "adj", ["lodging"], null, null],
    ["doble", "double (room)", "adj", ["lodging"], "Una habitación doble, por favor.", "A double room, please."],
    ["la llave", "the key", "noun", ["lodging"], "Perdí la llave.", "I lost the key."],
    ["la cama", "the bed", "noun", ["lodging"], null, null],
    ["el baño privado", "private bathroom", "noun", ["lodging"], "¿Tiene baño privado?", "Does it have a private bathroom?"],
    ["la ducha", "the shower", "noun", ["lodging"], "La ducha no tiene agua caliente.", "The shower doesn't have hot water."],
    ["la toalla", "the towel", "noun", ["lodging"], null, null],
    ["el jabón", "soap", "noun", ["lodging"], null, null],
    ["el papel higiénico", "toilet paper", "noun", ["lodging"], null, null],
    ["la almohada", "pillow", "noun", ["lodging"], null, null],
    ["la manta", "blanket", "noun", ["lodging"], null, null],
    ["el aire acondicionado", "air conditioning", "noun", ["lodging"], null, null],
    ["la calefacción", "heating", "noun", ["lodging"], null, null],
    ["el wifi", "WiFi", "noun", ["lodging"], "¿Cuál es la contraseña del wifi?", "What's the WiFi password?"],
    ["la contraseña", "the password", "noun", ["lodging"], null, null],
    ["el ascensor", "elevator", "noun", ["lodging"], null, null],
    ["la recepción", "the reception / front desk", "noun", ["lodging"], null, null],
    ["registrarse", "to check in", "verb", ["lodging"], "Quiero registrarme.", "I'd like to check in."],
    ["la salida", "checkout", "noun", ["lodging"], "¿A qué hora es la salida?", "What time is checkout?"],
    ["la caja fuerte", "safe (box)", "noun", ["lodging"], null, null],
    ["ruidoso/a", "noisy", "adj", ["lodging"], null, null],
    ["tranquilo/a", "quiet / calm", "adj", ["lodging"], "¿Tiene algo más tranquilo?", "Do you have something quieter?"],
    ["la vista", "the view", "noun", ["lodging"], null, null],
    ["desayuno incluido", "breakfast included", "phrase", ["lodging","food"], "¿El desayuno está incluido?", "Is breakfast included?"],
    ["reservar", "to book / reserve", "verb", ["lodging"], "Quiero reservar una habitación.", "I want to book a room."],
    ["disponible", "available", "adj", ["lodging"], null, null],
    ["una noche", "one night", "phrase", ["lodging"], "Para tres noches.", "For three nights."],
  ],
  "u11-money": [
    ["el dinero", "money", "noun", ["money"], "No tengo dinero.", "I don't have money."],
    ["el peso", "peso (currency)", "noun", ["money"], "¿Cuántos pesos?", "How many pesos?"],
    ["el dólar", "dollar", "noun", ["money"], null, null],
    ["el efectivo", "cash", "noun", ["money"], "Solo efectivo.", "Cash only."],
    ["la tarjeta", "card", "noun", ["money"], "¿Aceptan tarjeta?", "Do you accept card?"],
    ["la tarjeta de crédito", "credit card", "noun", ["money"], null, null],
    ["el cajero automático", "ATM", "noun", ["money"], "¿Hay un cajero cerca?", "Is there an ATM nearby?"],
    ["el cambio", "change / exchange", "noun", ["money"], "¿Tiene cambio?", "Do you have change?"],
    ["cambiar", "to change / exchange", "verb", ["money"], "¿Dónde puedo cambiar dólares?", "Where can I exchange dollars?"],
    ["caro/a", "expensive", "adj", ["money"], "Es muy caro.", "It's very expensive."],
    ["barato/a", "cheap", "adj", ["money"], "¿Tiene algo más barato?", "Do you have something cheaper?"],
    ["el descuento", "discount", "noun", ["money"], "¿Hay descuento?", "Is there a discount?"],
    ["gratis", "free (no cost)", "adj", ["money"], "La entrada es gratis.", "Entry is free."],
    ["la tienda", "the shop / store", "noun", ["money","shopping"], null, null],
    ["el mercado", "the market", "noun", ["money","shopping"], "Vamos al mercado.", "Let's go to the market."],
    ["pagar", "to pay", "verb", ["money"], "¿Dónde pago?", "Where do I pay?"],
    ["el recibo", "the receipt", "noun", ["money"], "¿Me da el recibo?", "Can you give me the receipt?"],
    ["la factura", "the invoice", "noun", ["money"], null, null],
    ["abierto/a", "open", "adj", ["money","schedule"], "¿Están abiertos?", "Are you open?"],
    ["cerrado/a", "closed", "adj", ["money","schedule"], "Está cerrado los domingos.", "It's closed on Sundays."],
    ["la talla", "the size (clothes)", "noun", ["shopping"], "¿Tiene talla mediana?", "Do you have medium size?"],
    ["probar", "to try (on)", "verb", ["shopping"], "¿Puedo probármelo?", "Can I try it on?"],
    ["devolver", "to return (an item)", "verb", ["shopping"], null, null],
    ["el regalo", "the gift", "noun", ["shopping"], "Es un regalo.", "It's a gift."],
    ["la bolsa", "the bag", "noun", ["shopping"], null, null],
  ],
  "u12-emergency": [
    ["la emergencia", "emergency", "noun", ["emergency"], null, null],
    ["la policía", "the police", "noun", ["emergency"], "Llame a la policía.", "Call the police."],
    ["el médico", "the doctor", "noun", ["emergency","health"], "Necesito un médico.", "I need a doctor."],
    ["el/la enfermero/a", "the nurse", "noun", ["emergency","health"], null, null],
    ["la medicina", "medicine", "noun", ["health"], "Necesito medicina para el dolor.", "I need pain medicine."],
    ["el dolor", "pain", "noun", ["health"], "Tengo dolor aquí.", "I have pain here."],
    ["me duele...", "my ... hurts", "phrase", ["health"], "Me duele la cabeza.", "My head hurts."],
    ["la fiebre", "fever", "noun", ["health"], "Tengo fiebre.", "I have a fever."],
    ["la gripe", "flu", "noun", ["health"], null, null],
    ["el resfriado", "cold (illness)", "noun", ["health"], null, null],
    ["la alergia", "allergy", "noun", ["health"], null, null],
    ["el estómago", "stomach", "noun", ["health","body"], "Me duele el estómago.", "My stomach hurts."],
    ["la ambulancia", "ambulance", "noun", ["emergency"], "Llame una ambulancia.", "Call an ambulance."],
    ["urgente", "urgent", "adj", ["emergency"], null, null],
    ["el peligro", "danger", "noun", ["emergency"], null, null],
    ["peligroso/a", "dangerous", "adj", ["emergency"], "Este barrio es peligroso de noche.", "This neighborhood is dangerous at night."],
    ["seguro/a", "safe / sure", "adj", ["emergency"], null, null],
    ["robar", "to rob / steal", "verb", ["emergency"], null, null],
    ["me robaron", "I was robbed", "phrase", ["emergency"], null, null],
    ["perdí...", "I lost...", "phrase", ["emergency"], "Perdí mi pasaporte.", "I lost my passport."],
    ["la embajada", "the embassy", "noun", ["emergency"], "¿Dónde está la embajada?", "Where is the embassy?"],
    ["llamar", "to call", "verb", ["emergency"], "¿Puede llamar a un doctor?", "Can you call a doctor?"],
    ["la receta", "the prescription", "noun", ["health"], "Necesito una receta.", "I need a prescription."],
    ["la pastilla", "the pill / tablet", "noun", ["health"], null, null],
    ["la venda", "bandage", "noun", ["health"], null, null],
    ["el seguro", "insurance", "noun", ["emergency"], "Tengo seguro de viaje.", "I have travel insurance."],
  ],
  "u13-people": [
    ["el hombre", "the man", "noun", ["people"], null, null],
    ["la mujer", "the woman", "noun", ["people"], null, null],
    ["el niño", "the boy / child", "noun", ["people"], null, null],
    ["la niña", "the girl", "noun", ["people"], null, null],
    ["el bebé", "the baby", "noun", ["people"], null, null],
    ["el padre", "the father", "noun", ["people","family"], null, null],
    ["la madre", "the mother", "noun", ["people","family"], null, null],
    ["el hijo", "the son", "noun", ["people","family"], null, null],
    ["la hija", "the daughter", "noun", ["people","family"], null, null],
    ["el hermano", "the brother", "noun", ["people","family"], null, null],
    ["la hermana", "the sister", "noun", ["people","family"], null, null],
    ["el abuelo", "the grandfather", "noun", ["people","family"], null, null],
    ["la abuela", "the grandmother", "noun", ["people","family"], null, null],
    ["el tío", "the uncle", "noun", ["people","family"], null, null],
    ["la tía", "the aunt", "noun", ["people","family"], null, null],
    ["el primo / la prima", "the cousin", "noun", ["people","family"], null, null],
    ["el esposo", "the husband", "noun", ["people","family"], null, null],
    ["la esposa", "the wife", "noun", ["people","family"], null, null],
    ["el novio / la novia", "boyfriend / girlfriend", "noun", ["people"], null, null],
    ["el amigo / la amiga", "friend", "noun", ["people"], "Es mi amigo.", "He's my friend."],
    ["la gente", "people (collective)", "noun", ["people"], "La gente aquí es muy amable.", "People here are very friendly."],
    ["el vecino / la vecina", "neighbor", "noun", ["people"], null, null],
    ["el señor", "sir / Mr.", "noun", ["people"], null, null],
    ["la señora", "ma'am / Mrs.", "noun", ["people"], null, null],
    ["joven", "young person / young", "noun", ["people"], null, null],
  ],
  "u14-adjectives": [
    ["grande", "big / large", "adj", ["descriptive"], null, null],
    ["pequeño/a", "small / little", "adj", ["descriptive"], null, null],
    ["alto/a", "tall / high", "adj", ["descriptive"], null, null],
    ["bajo/a", "short / low", "adj", ["descriptive"], null, null],
    ["joven", "young", "adj", ["descriptive"], null, null],
    ["viejo/a", "old", "adj", ["descriptive"], null, null],
    ["nuevo/a", "new", "adj", ["descriptive"], null, null],
    ["bueno/a", "good", "adj", ["descriptive"], null, null],
    ["malo/a", "bad", "adj", ["descriptive"], null, null],
    ["fácil", "easy", "adj", ["descriptive"], null, null],
    ["difícil", "difficult / hard", "adj", ["descriptive"], null, null],
    ["rápido/a", "fast / quick", "adj", ["descriptive"], null, null],
    ["lento/a", "slow", "adj", ["descriptive"], null, null],
    ["caliente", "hot (temperature)", "adj", ["descriptive"], "El café está caliente.", "The coffee is hot."],
    ["frío/a", "cold", "adj", ["descriptive"], null, null],
    ["lleno/a", "full", "adj", ["descriptive"], "Está lleno.", "It's full."],
    ["vacío/a", "empty", "adj", ["descriptive"], null, null],
    ["limpio/a", "clean", "adj", ["descriptive"], null, null],
    ["sucio/a", "dirty", "adj", ["descriptive"], null, null],
    ["fuerte", "strong / loud", "adj", ["descriptive"], null, null],
    ["débil", "weak", "adj", ["descriptive"], null, null],
    ["feliz", "happy", "adj", ["descriptive"], null, null],
    ["triste", "sad", "adj", ["descriptive"], null, null],
    ["bonito/a", "pretty / nice", "adj", ["descriptive"], "¡Qué bonito!", "How pretty!"],
    ["feo/a", "ugly", "adj", ["descriptive"], null, null],
    ["largo/a", "long", "adj", ["descriptive"], null, null],
    ["corto/a", "short (length)", "adj", ["descriptive"], null, null],
    ["ancho/a", "wide", "adj", ["descriptive"], null, null],
    ["listo/a", "ready / smart", "adj", ["descriptive"], "¿Estás listo?", "Are you ready?"],
    ["libre", "free (available/liberty)", "adj", ["descriptive"], "¿Está libre?", "Is it available?"],
  ],
  "u15-connectors": [
    ["en", "in / on / at", "prep", ["connector"], "Estoy en el hotel.", "I'm at the hotel."],
    ["de", "of / from", "prep", ["connector"], "Soy de Chile.", "I'm from Chile."],
    ["a", "to / at", "prep", ["connector"], "Voy a la tienda.", "I'm going to the shop."],
    ["con", "with", "prep", ["connector"], "Con leche, por favor.", "With milk, please."],
    ["sin", "without", "prep", ["connector"], "Sin azúcar.", "Without sugar."],
    ["por", "for / by / through", "prep", ["connector"], "Gracias por todo.", "Thanks for everything."],
    ["para", "for (purpose) / in order to", "prep", ["connector"], "Es para ti.", "It's for you."],
    ["sobre", "on top of / about", "prep", ["connector"], null, null],
    ["entre", "between / among", "prep", ["connector"], null, null],
    ["hasta", "until / up to", "prep", ["connector"], "Hasta mañana.", "Until tomorrow."],
    ["desde", "from / since", "prep", ["connector"], "Desde las ocho.", "Since eight o'clock."],
    ["durante", "during", "prep", ["connector"], null, null],
    ["y", "and", "conj", ["connector"], null, null],
    ["o", "or", "conj", ["connector"], null, null],
    ["pero", "but", "conj", ["connector"], "Me gusta, pero es caro.", "I like it, but it's expensive."],
    ["si", "if", "conj", ["connector"], "Si llueve, no voy.", "If it rains, I won't go."],
    ["como", "like / as", "prep", ["connector"], null, null],
    ["que", "that / which / who", "conj", ["connector"], "Creo que sí.", "I think so."],
    ["cuando", "when (not a question)", "conj", ["connector"], null, null],
    ["mientras", "while", "conj", ["connector"], null, null],
  ],
  "u16-body": [
    ["la cabeza", "head", "noun", ["body"], null, null],
    ["la cara", "face", "noun", ["body"], null, null],
    ["el ojo", "eye", "noun", ["body"], null, null],
    ["la nariz", "nose", "noun", ["body"], null, null],
    ["la boca", "mouth", "noun", ["body"], null, null],
    ["la oreja", "ear", "noun", ["body"], null, null],
    ["el diente", "tooth", "noun", ["body"], "Me duele un diente.", "My tooth hurts."],
    ["la mano", "hand", "noun", ["body"], null, null],
    ["el brazo", "arm", "noun", ["body"], null, null],
    ["la pierna", "leg", "noun", ["body"], null, null],
    ["el pie", "foot", "noun", ["body"], null, null],
    ["la espalda", "back (body)", "noun", ["body"], null, null],
    ["el dedo", "finger / toe", "noun", ["body"], null, null],
    ["el cuerpo", "body", "noun", ["body"], null, null],
    ["la ropa", "clothing", "noun", ["clothing"], "Necesito comprar ropa.", "I need to buy clothes."],
    ["la camisa", "shirt", "noun", ["clothing"], null, null],
    ["la camiseta", "t-shirt", "noun", ["clothing"], null, null],
    ["los pantalones", "pants / trousers", "noun", ["clothing"], null, null],
    ["el vestido", "dress", "noun", ["clothing"], null, null],
    ["los zapatos", "shoes", "noun", ["clothing"], null, null],
    ["las sandalias", "sandals", "noun", ["clothing"], null, null],
    ["el sombrero", "hat", "noun", ["clothing"], null, null],
    ["las gafas de sol", "sunglasses", "noun", ["clothing"], null, null],
    ["el abrigo", "coat", "noun", ["clothing"], null, null],
    ["la chaqueta", "jacket", "noun", ["clothing"], null, null],
    ["el suéter", "sweater", "noun", ["clothing"], null, null],
    ["la mochila", "backpack", "noun", ["clothing","travel"], null, null],
    ["el paraguas", "umbrella", "noun", ["clothing"], null, null],
    ["los calcetines", "socks", "noun", ["clothing"], null, null],
    ["la billetera", "wallet", "noun", ["clothing","money"], "Perdí mi billetera.", "I lost my wallet."],
  ],
};

// Expand gender abbreviations:
//   "amigo/a"        → display "amigo / amiga",     tts "amigo, amiga"
//   "el/la turista"  → display "el / la turista",    tts "turista"
//   "nosotros/as"    → display "nosotros / nosotras", tts "nosotros, nosotras"
//   "nuestro/a"      → display "nuestro / nuestra",  tts "nuestro, nuestra"
function expandGender(text) {
  // Pattern: "word<ending>/<alt>" e.g. "amigo/a", "nosotros/as", "primo/a"
  return text.replace(/(\S+?)(o|os)(\/)(a|as)\b/g, (_, stem, mascEnd, _slash, femEnd) => {
    return `${stem}${mascEnd} / ${stem}${femEnd}`;
  });
}

function expandGenderForTts(text) {
  return text.replace(/(\S+?)(o|os)(\/)(a|as)\b/g, (_, stem, mascEnd, _slash, femEnd) => {
    return `${stem}${mascEnd}, ${stem}${femEnd}`;
  });
}

// Handle "el/la" article pattern separately
function expandArticles(text) {
  return text.replace(/\bel\/la\b/g, "el / la")
             .replace(/\blos\/las\b/g, "los / las");
}

function expandDisplay(text) {
  return expandArticles(expandGender(text));
}

function expandTts(text) {
  let t = expandArticles(expandGenderForTts(text));
  // Strip "el / la " style article pairs
  t = t.replace(/\b(el|la|los|las|un|una) \/ (el|la|los|las|un|una) /g, "");
  // Replace remaining " / " with ", " so TTS pauses instead of saying "slash"
  t = t.replace(/ \/ /g, ", ");
  // Strip leading article
  t = t.replace(/^(el |la |los |las |un |una )/, "");
  // Strip articles after comma separator
  t = t.replace(/, (el |la |los |las |un |una )/g, ", ");
  return t;
}

// Build the deck.
const cards = [];
for (const [unitId, entries] of Object.entries(cardData)) {
  for (const entry of entries) {
    const [front, back, pos, tags, exFront, exBack] = entry;
    const id = unitId + "-" + slugify(front);
    const card = {
      id,
      front: expandDisplay(front),
      back,
      unit: unitId,
      pos,
    };
    if (tags && tags.length) card.tags = tags;
    if (exFront) card.exampleFront = exFront;
    if (exBack) card.exampleBack = exBack;
    card.ttsText = expandTts(front);
    cards.push(card);
  }
}

function slugify(s) {
  return s
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/gi, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase()
    .slice(0, 40);
}

const deck = { meta, units, cards };
const outPath = path.join(__dirname, "..", "decks", "spanish-traveler.json");
fs.writeFileSync(outPath, JSON.stringify(deck, null, 2));
console.log(`Wrote ${cards.length} cards to ${outPath}`);
